version: '3.8'

services:
  web:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips=*
    ports:
      - "8000:8000"
    volumes:
      - .:/app